package com.modelos.gestionmonitores;
// Generated 25-mar-2017 18:51:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblDocentes generated by hbm2java
 */
public class TblDocentes  implements java.io.Serializable {


     private String cedula;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String direccion;
     private Date fechaNacimiento;
     private String email;
     private String password;

    public TblDocentes() {
    }

	
    public TblDocentes(String cedula, String nombre, String apellidos, String email, String password) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.email = email;
        this.password = password;
    }
    public TblDocentes(String cedula, String nombre, String apellidos, String telefono, String direccion, Date fechaNacimiento, String email, String password) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.direccion = direccion;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.password = password;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


