package com.entidades.gestionmonitores;
// Generated 03-abr-2017 20:46:03 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblEstudiantes generated by hbm2java
 */
public class TblEstudiantes  implements java.io.Serializable {


     private String cedula;
     private String nombre;
     private String apellido;
     private String email;
     private Date fechaNacimiento;
     private String pwd;
     private String telefono;
     private String direccion;
     private boolean monitor;
     private char perfil;

    public TblEstudiantes() {
    }

	
    public TblEstudiantes(String cedula, String nombre, String apellido, String email, Date fechaNacimiento, String pwd, boolean monitor, char perfil) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.fechaNacimiento = fechaNacimiento;
        this.pwd = pwd;
        this.monitor = monitor;
        this.perfil = perfil;
    }
    public TblEstudiantes(String cedula, String nombre, String apellido, String email, Date fechaNacimiento, String pwd, String telefono, String direccion, boolean monitor, char perfil) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.fechaNacimiento = fechaNacimiento;
       this.pwd = pwd;
       this.telefono = telefono;
       this.direccion = direccion;
       this.monitor = monitor;
       this.perfil = perfil;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public boolean isMonitor() {
        return this.monitor;
    }
    
    public void setMonitor(boolean monitor) {
        this.monitor = monitor;
    }
    public char getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(char perfil) {
        this.perfil = perfil;
    }




}


