package com.entidades.gestionmonitores;
// Generated 03-abr-2017 20:46:03 by Hibernate Tools 4.3.1



/**
 * TblMaterias generated by hbm2java
 */
public class TblMaterias  implements java.io.Serializable {


     private String codigo;
     private String nombre;

    public TblMaterias() {
    }

    public TblMaterias(String codigo, String nombre) {
       this.codigo = codigo;
       this.nombre = nombre;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


